modLoader = "{{#if useKotlin}}kotlinforforge{{else}}neoforge{{/if}}"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL="${modIssues}"

[[mods]]
modId = "${modId}"
version = "${minecraftVersion}-neoforge-${modMyVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile="${modId}_small.png"
displayUrl="${modDiscord}"
modUrl="${modSource}"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforgeVersion},)"
ordering = "NONE"
side = "BOTH"